apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: test1
  labels:
    app: tomcat
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: tomcat
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: LoadBalancer
